export default {
  TOGGLE_EXPAND: 'TOGGLE_EXPAND',
  FETCH_ORDERS: 'FETCH_ORDERS',

  SET_DATA: 'SET_DATA',
  SELECT_ROW: 'SELECT_ROW',
  UNSELECT_ROW: 'UNSELECT_ROW',

  CHANGE_FIELD: 'CHANGE_FIELD',
};
